"""empty message

Revision ID: 002812ce27cb
Revises: bfb497364c82
Create Date: 2026-01-26 22:13:02.510883

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '002812ce27cb'
down_revision = 'bfb497364c82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.alter_column('driver_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.alter_column('driver_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
