"""empty message

Revision ID: 10f305aa7593
Revises: 136191df2ddb
Create Date: 2026-01-19 18:08:02.259974

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '10f305aa7593'
down_revision = '136191df2ddb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('permission',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('permission',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
