"""empty message

Revision ID: 12ba98d1d903
Revises: f13f98260797
Create Date: 2026-01-26 22:24:22.274153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12ba98d1d903'
down_revision = 'f13f98260797'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plate_number', sa.String(length=20), nullable=False))
        batch_op.create_unique_constraint(None, ['plate_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('plate_number')

    # ### end Alembic commands ###
