"""empty message

Revision ID: 136191df2ddb
Revises: 70f42ae2df74
Create Date: 2026-01-19 17:18:39.761845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '136191df2ddb'
down_revision = '70f42ae2df74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('permission', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('permission')

    # ### end Alembic commands ###
