"""empty message

Revision ID: 17aa3e93101b
Revises: fef3ffafe0e0
Create Date: 2026-01-28 18:48:27.530242

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '17aa3e93101b'
down_revision = 'fef3ffafe0e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('driver_returns', schema=None) as batch_op:
        batch_op.alter_column('platform',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('driver_returns', schema=None) as batch_op:
        batch_op.alter_column('platform',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###
