"""empty message

Revision ID: 1e14373621da
Revises: 355d407f8ced
Create Date: 2026-01-22 19:52:50.153016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e14373621da'
down_revision = '355d407f8ced'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_name', sa.String(length=80), nullable=False))
        batch_op.create_foreign_key(None, 'roles', ['role_name'], ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('role_name')

    # ### end Alembic commands ###
