"""empty message

Revision ID: 2dea64970e5f
Revises: f94ee0e0b927
Create Date: 2026-01-27 12:38:45.227900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dea64970e5f'
down_revision = 'f94ee0e0b927'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.add_column(sa.Column('brand_id', sa.String(length=30), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.drop_column('brand_id')

    # ### end Alembic commands ###
