"""empty message

Revision ID: 355d407f8ced
Revises: d52ae3079774
Create Date: 2026-01-22 19:34:23.872798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '355d407f8ced'
down_revision = 'd52ae3079774'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=80), nullable=False))
        batch_op.create_foreign_key(None, 'roles', ['role'], ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('role')

    # ### end Alembic commands ###
