"""empty message

Revision ID: 659c2beae79e
Revises: d0527be474d4
Create Date: 2026-01-26 21:42:00.944870

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '659c2beae79e'
down_revision = 'd0527be474d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drivers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=False))
        batch_op.drop_column('driver_name')
        batch_op.drop_column('driver_phone')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drivers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('driver_phone', mysql.VARCHAR(length=20), nullable=False))
        batch_op.add_column(sa.Column('driver_name', mysql.VARCHAR(length=50), nullable=False))
        batch_op.drop_column('phone')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
