"""empty message

Revision ID: b206b36a3304
Revises: 1e14373621da
Create Date: 2026-01-26 19:46:44.501471

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b206b36a3304'
down_revision = '1e14373621da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car_inventories', schema=None) as batch_op:
        batch_op.drop_column('id')

    with op.batch_alter_table('driver_profiles', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'car_inventories', ['plate_number'], ['plate_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('driver_profiles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('car_inventories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False))

    # ### end Alembic commands ###
