"""empty message

Revision ID: bfb497364c82
Revises: 659c2beae79e
Create Date: 2026-01-26 21:42:59.978188

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bfb497364c82'
down_revision = '659c2beae79e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drivers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('driver_name', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('driver_phone', sa.String(length=20), nullable=False))
        batch_op.drop_column('name')
        batch_op.drop_column('phone')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drivers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', mysql.VARCHAR(length=20), nullable=False))
        batch_op.add_column(sa.Column('name', mysql.VARCHAR(length=50), nullable=False))
        batch_op.drop_column('driver_phone')
        batch_op.drop_column('driver_name')

    # ### end Alembic commands ###
