"""empty message

Revision ID: c9b9116532de
Revises: d7238d7be334
Create Date: 2025-12-14 22:37:10.305226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9b9116532de'
down_revision = 'd7238d7be334'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accident_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('occurrence_date', sa.Date(), nullable=False),
    sa.Column('driver_name', sa.String(length=50), nullable=False),
    sa.Column('plate_number', sa.String(length=20), nullable=False),
    sa.Column('liability_determination', sa.String(length=100), nullable=False),
    sa.Column('accident_image_1', sa.String(length=255), nullable=True),
    sa.Column('accident_image_2', sa.String(length=255), nullable=True),
    sa.Column('accident_image_3', sa.String(length=255), nullable=True),
    sa.Column('accident_image_4', sa.String(length=255), nullable=True),
    sa.Column('case_number', sa.String(length=50), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('car_change_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver_name', sa.String(length=50), nullable=False),
    sa.Column('change_time', sa.DateTime(), nullable=False),
    sa.Column('original_plate', sa.String(length=20), nullable=False),
    sa.Column('new_plate', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('car_inventories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plate_number', sa.String(length=20), nullable=False),
    sa.Column('brand', sa.String(length=50), nullable=False),
    sa.Column('vehicle_model', sa.String(length=50), nullable=False),
    sa.Column('is_annual_inspected', sa.Boolean(), nullable=False),
    sa.Column('pickup_time', sa.DateTime(), nullable=False),
    sa.Column('is_in_use', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plate_number')
    )
    op.create_table('car_receipt_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('plate_number', sa.String(length=20), nullable=False),
    sa.Column('receipt_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('driver_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform_id', sa.String(length=50), nullable=False),
    sa.Column('driver_name', sa.String(length=50), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('plate_number', sa.String(length=20), nullable=False),
    sa.Column('vehicle_model', sa.String(length=50), nullable=False),
    sa.Column('driver_phone', sa.String(length=20), nullable=False),
    sa.Column('registration_date', sa.Date(), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('driver_returns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver_name', sa.String(length=50), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('plate_number', sa.String(length=20), nullable=False),
    sa.Column('driver_phone', sa.String(length=20), nullable=False),
    sa.Column('registration_date', sa.Date(), nullable=False),
    sa.Column('return_date', sa.Date(), nullable=False),
    sa.Column('is_over_30_days', sa.Boolean(), nullable=False),
    sa.Column('is_over_60_days', sa.Boolean(), nullable=False),
    sa.Column('is_over_90_days', sa.Boolean(), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vehicle_dynamics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plate_number', sa.String(length=20), nullable=False),
    sa.Column('fault_phenomenon', sa.Text(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('related_personnel', sa.String(length=100), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vehicle_dynamics')
    op.drop_table('driver_returns')
    op.drop_table('driver_profiles')
    op.drop_table('car_receipt_records')
    op.drop_table('car_inventories')
    op.drop_table('car_change_records')
    op.drop_table('accident_records')
    # ### end Alembic commands ###
