"""empty message

Revision ID: f13f98260797
Revises: 002812ce27cb
Create Date: 2026-01-26 22:23:21.198551

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f13f98260797'
down_revision = '002812ce27cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('plate_number'))
        batch_op.drop_column('plate_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plate_number', mysql.VARCHAR(length=20), nullable=False))
        batch_op.create_index(batch_op.f('plate_number'), ['plate_number'], unique=True)

    # ### end Alembic commands ###
