"""empty message

Revision ID: f2d99e53c182
Revises: b206b36a3304
Create Date: 2026-01-26 20:20:37.880184

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f2d99e53c182'
down_revision = 'b206b36a3304'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drivers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('driver_name', sa.String(length=50), nullable=False),
    sa.Column('driver_phone', sa.String(length=20), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cars',
    sa.Column('plate_number', sa.String(length=20), nullable=False),
    sa.Column('brand', sa.String(length=50), nullable=False),
    sa.Column('vehicle_model', sa.String(length=50), nullable=False),
    sa.Column('is_annual_inspected', sa.Boolean(), nullable=False),
    sa.Column('pickup_time', sa.DateTime(), nullable=False),
    sa.Column('is_in_use', sa.Boolean(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.PrimaryKeyConstraint('plate_number'),
    sa.UniqueConstraint('plate_number')
    )
    op.drop_table('driver_profiles')
    with op.batch_alter_table('car_inventories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('plate_number'))

    op.drop_table('car_inventories')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car_inventories',
    sa.Column('plate_number', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('brand', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('vehicle_model', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('is_annual_inspected', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('pickup_time', mysql.DATETIME(), nullable=False),
    sa.Column('is_in_use', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('car_inventories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('plate_number'), ['plate_number'], unique=True)

    op.create_table('driver_profiles',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('platform_id', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('driver_name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('platform', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('plate_number', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('vehicle_model', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('driver_phone', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('registration_date', sa.DATE(), nullable=False),
    sa.Column('remarks', mysql.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['plate_number'], ['car_inventories.plate_number'], name=op.f('driver_profiles_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('cars')
    op.drop_table('drivers')
    # ### end Alembic commands ###
